### PR TITLE
Added an optional "uid" parameter to createStyles...

### PR DESCRIPTION
**Pull request by k7n4n5t3w4rt**
… for passing in a unique identifier - and not generating one dynamically.

I imagine you won't want to merge this into #master as I've not used TypeScript before and probably haven't implemented this how you would do it anyway. Just raising this pull request for discussion purposes.

I'm using `simplestyle-js` with Snowpack and it's great. When server-side rendering and using hydrate() instead of render(), `simplestyle-js` is kicking in again on the client-side and generating new CSS class names for the `<style>` insert - but it can't update the classNames in the component that was rendered on the server. So the CSS class names don't match.

I was thinking that, for me, a good fix would be to pass in a unique identifier for `simplestyle-js` to use instead of generating one.

### CODE REVIEW

**Comment by benduran** [comment]
@k7n4n5t3w4rt thanks for the submission. Apologies for not reviewing sooner. My Github notifications were buried underneath all of the COVID and marketing emails. I will review in the next 24 hours and we can go from there 👍

**Comment by benduran** [comment]
@k7n4n5t3w4rt could you share some potential sample code, if possible? I'm curious as to where you're creating your styles, whether that's inside or outside the scope of your component.

Also, if you have any spare time, if you could modify this PR to include a sample test case you would expect to pass, but actually fails for this use case. That would be incredibly useful for identifying whether setting a pre-determined uid for the generated class is the best approach. Let me know!

**Comment by k7n4n5t3w4rt** [comment]
Here's an example of a component from the boilerplate I'm using for new projects. I'm setting the unique identifier to "myuniqueid". I'm interested to know if I'm using it correctly or not.

I'm not sure I can do a test, since the problem only manifests for me when I'm using `simplestyle` in a project and rendering server-side. It would have to be a test in [my example project](https://github.com/k7n4n5t3w4rt/es-module-preact-boilerplate) 

```
import { h, render } from "../web_modules/preact.js";
import { useState } from "../web_modules/preact/hooks.js";
import htm from "../web_modules/htm.js";
import { createStyles, rawStyles } from "../web_modules/simplestyle-js.js";

const html = htm.bind(h);
rawStyles({
  html: {
    height: "100%",
  },
  body: {
    height: "100%",
  },
});

const [styles] = createStyles(
  {
    container: {
      fontFamily: "sans-serif",
      textAlign: "center",
      height: "100%",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
    },
    heading: {
      fontSize: "2em",
      color: "gold",
    },
    counter: {
      fontSize: "7em",
      color: "silver",
      lineHeight: "0.05em",
    },
    buttons: {
      fontSize: "4em",
    },
  },
  null,
  "myuniqueid",
);

/*::
type Props = {
  count: typeof Number
};
*/
const Counter = (props) => {
  const [count, setCount] = useState(parseInt(props.count));

  return html`
    <div className="${styles.container}">
      <h1 className="${styles.heading}">
        No script tags.<br />
        No build step.
      </h1>
      <div>
        <h2 className="${styles.counter}">${count}</h2>
        <button
          className="${styles.buttons}"
          onClick=${e => setCount(count - 1)}
        >
          -
        </button>
        <button
          className="${styles.buttons}"
          onClick=${e => setCount(count + 1)}
        >
          +
        </button>
      </div>
    </div>
  `;
};

export default Counter;
```

**Comment by benduran** [comment]
Thanks for sharing. The code looks totally reasonable. Nothing seems obviously out-of-place.

On the Simplestyle-js side of things, I think a little more thought might need to be put in with regards to server-side rendering. Ideally, the usage of the library on the server should not deviate from in-browser, or if it does, its deviation should be very minor.

You could probably hack your way around this by setting `{ flush: false }` and then handle rendering the stylesheets yourself, but that  in the options, but I think that might require too much code on your end for what you're trying to achieve.

Passing-in some type of pre-generated UID could work, though I'm not 100% it is the ideal solution. Perhaps an additional `{ cache: true }` option could be provided and, if it is set, would cache the generated CSS classnames in-memory. This could then attempt to reuse the cached selectors on subsequent calls 🤔  Let me brainstorm on this a bit. If this is blocking you from performing some critical work, though, let me know, and I'll do my best to prioritize accordingly.

If you have any other random off-the-wall ideas too, please let me know 😄

**Comment by benduran** [comment]
Another idea would be to allow you to provide your starting "seed" for the classname generation. Assuming your modules are imported in the same order each time, setting an initial seed would ensure a reliable and deterministic way to generate the CSS classnames you can use in your components.

**Comment by benduran** [comment]
Issued a PR for the proposed "seed" feature, and added two tests. I _think_ this might cheaply accomplish what you need: https://github.com/benduran/simplestyle/pull/20

take a look and let me know if that seems reasonable. If it does, I'll merge and publish to a beta channel if you want to test it out

**Comment by k7n4n5t3w4rt** [comment]
That looks good! I didn’t really look closely at how the suffix it being generated. Looking just now, it seems to me that it will generate the same suffix if given the same seed across successive calls - good for server-side rendering of the component and subsequent client-side “hydration” of the CSS.

It would be good, wouldn’t it, if the <styles> could be in the mark-up generated by the component rather than in the <head>. That way the CSS could be rendered server-side with the markup. That would be a better experience for the user as right now the CSS is loaded after page load so there’s a moment of no-css layout before the styling kicks in. However, that seems invalid, which I’m sure is why you put the <styles> in the <head>. Still… pity.

**Comment by benduran** [comment]
@k7n4n5t3w4rt version `2.2.0` has been published. Give it a shot and please do let me know if it works out for you 👍 

Closing this PR. Thanks for the discussion!

**Pull request closed without merging**
